Adicionando envio de arquivo
NExT-2023-1/n01-envio-de-arquivos pull request #3
Opened 2023-09-14 22:46 UTC by julio-marques

2023-09-15 22:43 UTC, MichaelBittencourt requested changes

2023-09-15 22:43 UTC, MichaelBittencourt commented on envio-arquivos/ARQUIVO/.vscode/settings.json
> +{
Esse arquivo não é necessário, remover.

2023-09-15 22:43 UTC, MichaelBittencourt commented on envio-arquivos/ARQUIVO/bin/App.class
adicionar arquivos .class no gitignore. Remover

2023-09-15 22:43 UTC, MichaelBittencourt commented on envio-arquivos/ARQUIVO/bin/upload/UploadaArquivo.class
adicionar .class no gitignore. Remover

2023-09-15 22:43 UTC, MichaelBittencourt commented on envio-arquivos/ARQUIVO/src/upload/UploadaArquivo.java
> +public class UploadaArquivo {
Typo. Ajustar nome da classe para UploadArquivo.

2023-09-15 22:43 UTC, MichaelBittencourt commented on envio-arquivos/ARQUIVO/src/upload/UploadaArquivo.java
> +           //URLConnection connection = new URL(url).openConnection();
Remover códigos comentados

2023-09-19 00:03 UTC, julio-marques commented on envio-arquivos/ARQUIVO/.vscode/settings.json
> +{
Removido

2023-09-19 00:15 UTC, julio-marques commented on envio-arquivos/ARQUIVO/bin/App.class
Resolvi

2023-09-19 00:15 UTC, julio-marques commented on envio-arquivos/ARQUIVO/bin/upload/UploadaArquivo.class
Resolvi

2023-09-19 00:19 UTC, julio-marques commented on envio-arquivos/ARQUIVO/src/upload/UploadaArquivo.java
> +public class UploadaArquivo {
Resolvi

2023-09-19 00:19 UTC, julio-marques commented on envio-arquivos/ARQUIVO/src/upload/UploadaArquivo.java
> +           //URLConnection connection = new URL(url).openConnection();
Resolvi

2023-09-19 00:25 UTC, MichaelBittencourt approved these changes

2023-09-19 00:26 UTC, merged